# Makefile - for Fast-CDR
#
# Copyright (c) 2019 Wind River Systems, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# modification history
# --------------------
# 22jan19,akh  uprev to 1.0.8
# 27jun18,rcw  Updated
# 18mar18,akh  created
#


PKG_NAME = fastcdr
PKG_VER = 1.0.8
PKG_TYPE = git
PKG_LICENSE = Apache 2.0

PKG_URL = https://github.com/eProsima/Fast-CDR.git
PKG_COMMIT_ID = v1.0.8
PKG_DIR_NAME = fast-cdr

PKG_BUILD_DIR = fast-cdr
PKG_SRC_DIR = fast-cdr

include $(WIND_USR_MK)/defs.packages.mk
include $(WIND_USR_MK)/defs.crossbuild.mk
include $(WIND_USR_MK)/rules.packages.mk
