# Makefile -  Makefile for a VSB Layer
#
# Copyright 2018, Wind River Systems, Inc.
#      
# This software is released under the terms of the 
# Python Software Foundation License Version 2
# included in this repository in the LICENSE file
# or at https://docs.python.org/3/license.html
#
# modification history
# -------------------- 
# 24sep18,akh  create


#PRE_BUILD_DIRS = usr_src

POSTBUILD_RTP_DIRS = usr_src

include $(WIND_KRNL_MK)/rules.layers.mk
