# layer.vsbl file for tinyxml2
#
# Copyright (c) 2019 Wind River Systems, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Modification history
# --------------------
# 26jun18,rcw Updated
# 2oct17,cai  created
#


PRE_BUILD_DIRS = user_src

# POSTBUILD_USRLIB_DIRS = user_src

POSTBUILD_RTP_DIRS = user_src


include $(WIND_KRNL_MK)/rules.layers.mk

