# Makefile - for rcl
#
# Copyright (c) 2019 Wind River Systems, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# modification history
# --------------------
# 06aug18,akh  created
#

PKG_NAME = rcl
PKG_VER = 0.5.0
PKG_TYPE = git
PKG_COMMIT_ID = bouncy
PKG_LICENSE = Apache 2.0

PKG_URL =  https://github.com/ros2/$(PKG_NAME).git

PKG_BUILD_DIR = $(PKG_NAME)
PKG_SRC_DIR = $(PKG_NAME)

include $(WIND_USR_MK)/defs.packages.mk
include $(WIND_USR_MK)/defs.crossbuild.mk
include $(WIND_USR_MK)/rules.packages.mk

